### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by midi** [diederich/moneymoney-monzo#1] opened 2018-07-22 06:58 UTC
Hi, I'm using the extension with my own API details.
Once I start the account setup, I'm getting to the dialogue where it asks for my email.
Upon entering, then button to request the email does not give any result.
It works outside of the app, with my email address.
Is this reproducible for you?

I'm running 2.3.6. Beta with extension validation disabled.
Do not see any errors in the console.

**Comment by diederich** [comment] 2018-07-22 08:52
Hey! I’m on my way to Boom Festival, but the last time I checked it was still working - probably on Thursday/Friday, so I’d assume it’s fine? ;-)
I can’t remember if we had to put something specific regarding my api credentials into Money Money - maybe that’s the issue?
I think I could add your userid to the app if that’s something you wanna try? 
Also - thanks for testing. I think you might be the first one :-)

**Comment by midi** [comment] 2018-07-23 23:58
Hmm, maybe it's only the setup process. I will tinker a bit more.
I'd rather keep my userid private, but thanks for the offer and the extension :)
I'll report back should I find a way to fix it.

**Comment by hendryque** [comment] 2018-11-06 08:03
Can reproduce that for 2.3.8. Not able to login, nothing happens when I click on "submit".

**Comment by gdelmas** [comment] 2018-11-24 16:58
hey @midi and @diederich ,

i have exactly the same problem. the button does not do anything. the logs just show: `Sending: POST https://api.monzo.com/oauth2/authorize`

were you able to solve this?

**Comment by diederich** [comment] 2018-11-24 19:05
Hey @gedelmas!
I’m using it at least once a week, so it’s generally possible to work :-)

I’m not sure what it is with the setup. IIRC someone else commented  to this recently as well, but then deleted the comment again. (So it might just be something that’s easily overlooked ;-))
So let us know / post back when you figure something out!

**Comment by gdelmas** [comment] 2018-11-24 21:41
might there have been some whitelisting by @mrh-line? the extension i am using is obviously not signed anymore, after changing the oauth client id and secret.

@mrh-line is there any way to open developer tools in the browser window?

**Comment by gdelmas** [comment] 2018-11-25 02:02
looks like passing the `redirect_uri` by parameter alone is not enough or might not even have any effect. `moneymoney-app://oauth` has to be set on the monzo developer dashboard as `Redirect URLs`.

**Comment by mrh-line** [comment] 2018-11-25 08:26
@gdelmas Please call the menu function »Window« → »Log« in MoneyMoney to see the error messages. If in doubt about the sent HTTP headers or HTTP POST content, insert a print() into the Lua script.

**Comment by diederich** [comment] 2018-11-26 13:59
Should be fixed with #2 thanks to @gdelmas 🎆 🍾

**Closed as completed by diederich** 2018-11-26 13:59 UTC
